# Generated by Django 5.0.6 on 2024-07-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batuda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apc',
            name='code',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
