# Generated by Django 5.0.6 on 2024-07-01 07:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batuda', '0002_alter_apc_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntingRaid',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, spatial_index=False, srid=4326)),
            ],
            options={
                'verbose_name': 'Àrea privada de caça',
                'verbose_name_plural': 'Àrees privades de caça',
            },
        ),
        migrations.DeleteModel(
            name='Apc',
        ),
    ]
